name: MC_Crasher
version: 1.0
main: cb.sektory.mccrasher.MC_Crasher
depend: [ProtocolLib]
commands:
  mccrash:
    description: Wywala minecrafta wybranemu graczowi
    usage: /mccrash <player>
  pingplayer:
    description: Ustawia symulowany ping dla gracza.
    usage: /pingplayer <nick gracza> <wartość pingu>
